In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [49]:
gold_data=yf.download("GLD",start='2020-01-01',end='2026-06-30')

gold=pd.DataFrame(gold_data)
gold.head()

/tmp/ipykernel_12814/1489316306.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  gold_data=yf.download("GLD",start='2020-01-01',end='2026-06-30')
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker             GLD         GLD         GLD         GLD       GLD
Date
2020-01-02  143.949997  144.210007  143.399994  143.860001   7733800
2020-01-03  145.860001  146.320007  145.399994  145.750000  12272800
2020-01-06  147.389999  148.479996  146.949997  148.440002  14403300
2020-01-07  147.970001  148.139999  147.429993  147.570007   7978500
2020-01-08  146.860001  148.610001  146.139999  148.490005  22248500

In [40]:
X,y=gold[['High','Low','Open']],gold['Close']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)
y_train=np.array(y_train)
y_test=np.array(y_test)

In [20]:
class myLR:
  def __init__(self):
    self.coef_ = None
    self.intercept_ = None

  def fit(self, X_train, y_train):
    X_train=np.insert(X_train,0,1,axis=1)

    betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    print(betas)

    self.intercept_=betas[0]
    self.coef_=betas[1:]

  def predict(self,X_test):
    y_pred=np.dot(X_test,self.coef_)+self.intercept_
    return y_pred

In [44]:
lr=myLR()
lr.fit(X_train,y_train)

[[-0.0364648 ]
 [ 0.87466282]
 [ 0.63127513]
 [-0.50663094]]

In [57]:
y_pred=lr.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.9996870054069215
2.042691973085754

In [48]:
comparsion=pd.DataFrame(np.c_[y_test,y_pred],columns=['Actual','Predicted'])
comparsion

         Actual   Predicted
0    196.009995  195.715321
1    279.959991  279.353625
2    230.289993  229.149654
3    229.369995  228.860779
4    173.619995  173.714357
..          ...         ...
321  163.479996  162.952313
322  172.529999  172.440412
323  307.399994  306.976142
324  162.619995  163.134803
325  172.850006  172.822966

[326 rows x 2 columns]